/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sctp2.Paciente;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import sctp2.Pesquisar.Pesquisar;
import sctp2.Pesquisar.PesquisarProntuarioStatico;

/**
 *
 * @author Adriano
 */
public class DadosDoPaciente extends javax.swing.JFrame {

    String rgPaciente;//esta variavel irá ser preenchida com o valor passado pelo construtor desta interface sendo este o rg
    int pacientelistaNegra;//recebe o valor de lista negra;
    int codigopaciente;
    int statusdotratamento;//variavel que recebe o valor do status do tratament: ativo, finalizado
    Color background;//pega a cor de fundo de um campo

    /**
     * Creates new form Paciente
     */
    public DadosDoPaciente() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        BloqueiaCampos();//impede a edição dos campos
        jbCancelaEdicao.setVisible(false);
        jBSalvar.setEnabled(false);

    }

    public DadosDoPaciente(String rg) throws ClassNotFoundException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        SetValoresCampos(rg);
        PesquisaProntuario();
        BloqueiaCampos();//impede a edição dos campos
        jbCancelaEdicao.setVisible(false);
        rgPaciente = rg;
        jBSalvar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBVoltar = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbCancelaEdicao = new javax.swing.JButton();
        jRetiraListaNegra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLOcupacao = new javax.swing.JLabel();
        jLPai = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jocupação = new javax.swing.JTextField();
        jpai = new javax.swing.JTextField();
        jLNasc = new javax.swing.JLabel();
        jLMae = new javax.swing.JLabel();
        jLRG = new javax.swing.JLabel();
        jMae = new javax.swing.JTextField();
        jrg = new javax.swing.JTextField();
        jLNaturalidade = new javax.swing.JLabel();
        jnaturalidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jsexo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jprocedencia = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jestadocivil = new javax.swing.JComboBox();
        jLConjuge = new javax.swing.JLabel();
        jconjuge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLRua = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLTelContato = new javax.swing.JLabel();
        jbairro = new javax.swing.JTextField();
        jcidade = new javax.swing.JTextField();
        jtelefone = new javax.swing.JFormattedTextField();
        jrua = new javax.swing.JTextField();
        jnumeroDoEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLCep = new javax.swing.JLabel();
        jcep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistaNegraJustificativa = new javax.swing.JTextPane();
        jNotificao = new javax.swing.JTextField();
        jTelefoneFixo = new javax.swing.JTextField();
        jLTelContato1 = new javax.swing.JLabel();
        jnascimento = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTratamento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jNovoTratamento = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jprontuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JdescricaoProntuario = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jresponsavelprontuario = new javax.swing.JTextField();
        jsituacaoprontuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jcelularprontuario = new javax.swing.JTextField();
        jtelefonfixoprontuario = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Paciente");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jBVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jBVoltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBVoltar.setForeground(new java.awt.Color(0, 0, 255));
        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left-arrow.png"))); // NOI18N
        jBVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jBVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBVoltarMouseClicked(evt);
            }
        });
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jBSalvar.setForeground(new java.awt.Color(0, 0, 255));
        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save5.png"))); // NOI18N
        jBSalvar.setText("Salvar alterações");
        jBSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new java.awt.Color(255, 255, 255));
        jBEditar.setForeground(new java.awt.Color(0, 0, 255));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar pqno.png"))); // NOI18N
        jBEditar.setText("Editar");
        jBEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir pequeno.png"))); // NOI18N
        jButton2.setText("Excluir");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbCancelaEdicao.setBackground(new java.awt.Color(255, 255, 255));
        jbCancelaEdicao.setForeground(new java.awt.Color(0, 51, 153));
        jbCancelaEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar pequeno.png"))); // NOI18N
        jbCancelaEdicao.setText("Cancelar Edição");
        jbCancelaEdicao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jbCancelaEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelaEdicaoActionPerformed(evt);
            }
        });

        jRetiraListaNegra.setBackground(new java.awt.Color(255, 255, 255));
        jRetiraListaNegra.setForeground(new java.awt.Color(0, 0, 255));
        jRetiraListaNegra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/REMOVE.png"))); // NOI18N
        jRetiraListaNegra.setText("Retirar da Lista Negra");
        jRetiraListaNegra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 50, 255), 1, true));
        jRetiraListaNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetiraListaNegraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRetiraListaNegra, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRetiraListaNegra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbCancelaEdicao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalhes do Paciente");

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setForeground(new java.awt.Color(51, 102, 255));
        jLNome.setText("Nome:");

        jLOcupacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLOcupacao.setForeground(new java.awt.Color(51, 102, 255));
        jLOcupacao.setText("Ocupação:");

        jLPai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPai.setForeground(new java.awt.Color(51, 102, 255));
        jLPai.setText("Pai:");

        jNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jocupação.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jocupação.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jpai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpai.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLNasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNasc.setForeground(new java.awt.Color(51, 102, 255));
        jLNasc.setText("Nasc:");

        jLMae.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLMae.setForeground(new java.awt.Color(51, 102, 255));
        jLMae.setText("Mãe:");

        jLRG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLRG.setForeground(new java.awt.Color(51, 102, 255));
        jLRG.setText("RG:");

        jMae.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMae.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrg.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLNaturalidade.setForeground(new java.awt.Color(51, 102, 255));
        jLNaturalidade.setText("Nat:");

        jnaturalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnaturalidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnaturalidadeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Sexo: ");

        jsexo.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jsexo.setForeground(new java.awt.Color(0, 51, 51));
        jsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino" }));
        jsexo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Procedência: ");

        jprocedencia.setForeground(new java.awt.Color(51, 0, 51));
        jprocedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zona Urbana", "Zona Rural" }));
        jprocedencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Estado civil: ");

        jestadocivil.setForeground(new java.awt.Color(51, 0, 51));
        jestadocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Viúvo", "Divorciado" }));
        jestadocivil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jestadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jestadocivilActionPerformed(evt);
            }
        });

        jLConjuge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLConjuge.setForeground(new java.awt.Color(51, 102, 255));
        jLConjuge.setText("Cônjuge:");

        jconjuge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jconjuge.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Endereço");

        jLRua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLRua.setForeground(new java.awt.Color(51, 102, 255));
        jLRua.setText("Rua:");

        jLBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLBairro.setForeground(new java.awt.Color(51, 102, 255));
        jLBairro.setText("Bairro:");

        jLCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCidade.setForeground(new java.awt.Color(51, 102, 255));
        jLCidade.setText("Cidade:");

        jLTelContato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTelContato.setForeground(new java.awt.Color(51, 102, 255));
        jLTelContato.setText("Fixo:");

        jbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jcidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        try {
            jtelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jrua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrua.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jnumeroDoEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnumeroDoEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Número:");

        jLCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCep.setForeground(new java.awt.Color(51, 102, 255));
        jLCep.setText("CEP:");

        try {
            jcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcep.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lista Negra (Preencha este campo SOMENTE se o paciente estiver na lista negra):");

        jlistaNegraJustificativa.setBackground(new java.awt.Color(204, 204, 204));
        jlistaNegraJustificativa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 50, 255)));
        jScrollPane1.setViewportView(jlistaNegraJustificativa);

        jNotificao.setEditable(false);
        jNotificao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNotificao.setForeground(java.awt.Color.red);
        jNotificao.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTelefoneFixo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLTelContato1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTelContato1.setForeground(new java.awt.Color(51, 102, 255));
        jLTelContato1.setText("Celular:");

        jnascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Situação do paciente");

        jTratamento.setEditable(false);
        jTratamento.setBackground(new java.awt.Color(255, 255, 255));
        jTratamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTratamento.setForeground(new java.awt.Color(255, 102, 0));
        jTratamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fim.png"))); // NOI18N
        jButton1.setText("Finalizar tratamento");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/detalhes.png"))); // NOI18N
        jButton3.setText("Detalhes do tratamento atual");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(51, 102, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/history.png"))); // NOI18N
        jButton4.setText("Histórico de tratamentos");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jNovoTratamento.setBackground(new java.awt.Color(255, 255, 255));
        jNovoTratamento.setForeground(new java.awt.Color(0, 51, 255));
        jNovoTratamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mais.png"))); // NOI18N
        jNovoTratamento.setText("Adicionar  Tratamento");
        jNovoTratamento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        jNovoTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoTratamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTratamento)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNovoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jNovoTratamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel8.setText("Prontuário: ");

        jprontuario.setBorder(null);

        JdescricaoProntuario.setEditable(false);
        JdescricaoProntuario.setColumns(20);
        JdescricaoProntuario.setRows(5);
        jScrollPane2.setViewportView(JdescricaoProntuario);

        jLabel10.setText("Descrição:");

        jLabel11.setText("Situação:");

        jLabel12.setText("Responsável");

        jresponsavelprontuario.setBorder(null);

        jsituacaoprontuario.setBorder(null);
        jsituacaoprontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsituacaoprontuarioActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefone: ");

        jcelularprontuario.setBorder(null);

        jtelefonfixoprontuario.setBorder(null);
        jtelefonfixoprontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtelefonfixoprontuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLOcupacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLPai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel2))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jNome, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                            .addComponent(jocupação)
                                            .addComponent(jpai)
                                            .addComponent(jsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLMae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLRG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jrg)
                                            .addComponent(jMae)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLCep, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLTelContato1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnumeroDoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLTelContato)
                                                .addGap(10, 10, 10)
                                                .addComponent(jTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jprocedencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jconjuge))))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLRua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrua, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jNotificao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jsituacaoprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtelefonfixoprontuario)
                                                    .addComponent(jcelularprontuario)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jresponsavelprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNome)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNaturalidade)
                                .addComponent(jnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jocupação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLRG)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLMae, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLRua)
                                    .addComponent(jrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jnumeroDoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLBairro)
                                    .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLCep)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jprocedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jconjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCidade)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLTelContato1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLTelContato, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jsituacaoprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jresponsavelprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jtelefonfixoprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcelularprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNotificao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/detalhes.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dente branco.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnaturalidadeActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        boolean retorno;
        retorno = VerificaCampos();//função quer verifica se os campos obrigatorios foram preenchidos
        if (retorno == false) {
            jNotificao.setText("Corrija ou preencha os campos em vermelho para continuar.");
        }
        if (retorno == true) {
            System.out.println("rg: " + rgPaciente);
            SetValoresPaciente();//função que passara para a classe de controle Paciente os dados de entrada
            sctp2.ClassesdeControle.Controle acesso = new sctp2.ClassesdeControle.Controle();
            try {
                retorno = acesso.AtualizaPaciente();
                if (retorno == true) {
                    BloqueiaCampos();
                    jbCancelaEdicao.setVisible(false);
                    jBEditar.setVisible(true);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
//        SetValoresPaciente();
        sctp2.Paciente.PesquisarPaciente acesso = new sctp2.Paciente.PesquisarPaciente();
        this.setVisible(false);
        acesso.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jestadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jestadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jestadocivilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
        sctp2.Principal.principal acesso = new sctp2.Principal.principal();
        acesso.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        AtivaCampos();
        jBEditar.setVisible(false);
        jbCancelaEdicao.setVisible(true);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jbCancelaEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelaEdicaoActionPerformed
        BloqueiaCampos();
        jbCancelaEdicao.setVisible(false);
        jBEditar.setVisible(true);
    }//GEN-LAST:event_jbCancelaEdicaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean retorno = false;
        int confirma;
        sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
        confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este paciente?");
        if (confirma == 0) {
            try {
                retorno = acesso.ExcluiCadastro(rgPaciente);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (retorno == true) {
                sctp2.Paciente.PesquisarPaciente Vai = new sctp2.Paciente.PesquisarPaciente();
                Vai.setVisible(true);//chama a tela de pesquisar paciente
                this.setVisible(false);
            } else if (retorno == false) {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o paciente!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBVoltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVoltarMouseClicked

    private void jRetiraListaNegraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetiraListaNegraActionPerformed
        if (pacientelistaNegra == 1) {
            int resposta = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja retirar este paciente da lista negra?");
            if (resposta == 0) {
                sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
                boolean retorno;
                try {
                    retorno = acesso.MudaStatusListaNegraPaciente(rgPaciente);
                    if (retorno == true) {
                        SetValoresCampos(rgPaciente);
                        jNotificao.setText("O paciente foi retirado da lista Negra");
                        pacientelistaNegra = 0;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }//fim do if paciente lista negra==1
        else if (pacientelistaNegra == 0) {
            new sctp2.Paciente.ColocarnaListaNegra(jNome.getText(), codigopaciente, rgPaciente).setVisible(true);
            this.setVisible(false);
            pacientelistaNegra = 1;
        }
    }//GEN-LAST:event_jRetiraListaNegraActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            new sctp2.Paciente.PacientetratamentoEdoencas(rgPaciente, jNome.getText()).setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jsituacaoprontuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsituacaoprontuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsituacaoprontuarioActionPerformed

    private void jtelefonfixoprontuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtelefonfixoprontuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtelefonfixoprontuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FinalizarTratamento acesso;
        try {
            acesso = new FinalizarTratamento(rgPaciente);
            acesso.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }

//        int resposta = JOptionPane.showConfirmDialog(rootPane, "Confirma o encerramento deste tratamento?");
//        if (resposta == 0) {
//            sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
//            boolean retorno;
//            try {
//                retorno = acesso.EncerraTratamento(jrg.getText());
//                if (retorno == true) {
//                    jNotificao.setText("Tratamento Finalizado");
//                    jTratamento.setText("Tratamento Finalizado");
//                    jButton1.setEnabled(false);//desabilita o botao finalizar tratamento
//                    jButton1.setVisible(true);
//                    jNovoTratamento.setEnabled(true);
//                    GravaTratamentoNoHistorico();
//                }
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            new sctp2.Paciente.HistoricoDoPaciente(codigopaciente, jrg.getText()).setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jNovoTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoTratamentoActionPerformed
        this.setVisible(false);
        try {
            new sctp2.NovoTratamento.Prontuario(jrg.getText()).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DadosDoPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jNovoTratamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosDoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosDoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosDoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosDoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosDoPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JdescricaoProntuario;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLConjuge;
    private javax.swing.JLabel jLMae;
    private javax.swing.JLabel jLNasc;
    private javax.swing.JLabel jLNaturalidade;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLOcupacao;
    private javax.swing.JLabel jLPai;
    private javax.swing.JLabel jLRG;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLTelContato;
    private javax.swing.JLabel jLTelContato1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMae;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jNotificao;
    private javax.swing.JButton jNovoTratamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jRetiraListaNegra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTelefoneFixo;
    private javax.swing.JTextField jTratamento;
    private javax.swing.JButton jbCancelaEdicao;
    private javax.swing.JTextField jbairro;
    private javax.swing.JTextField jcelularprontuario;
    private javax.swing.JFormattedTextField jcep;
    private javax.swing.JTextField jcidade;
    private javax.swing.JTextField jconjuge;
    private javax.swing.JComboBox jestadocivil;
    private javax.swing.JTextPane jlistaNegraJustificativa;
    private javax.swing.JTextField jnascimento;
    private javax.swing.JTextField jnaturalidade;
    private javax.swing.JTextField jnumeroDoEndereco;
    private javax.swing.JTextField jocupação;
    private javax.swing.JTextField jpai;
    private javax.swing.JComboBox jprocedencia;
    private javax.swing.JTextField jprontuario;
    private javax.swing.JTextField jresponsavelprontuario;
    private javax.swing.JTextField jrg;
    private javax.swing.JTextField jrua;
    private javax.swing.JComboBox jsexo;
    private javax.swing.JTextField jsituacaoprontuario;
    private javax.swing.JFormattedTextField jtelefone;
    private javax.swing.JTextField jtelefonfixoprontuario;
    // End of variables declaration//GEN-END:variables

    private void SetValoresCampos(String rg) throws ClassNotFoundException {
        //Esta função recebe os dados do banco de dados e carrega tudo nos campos da interface 
        sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
        ArrayList<Pesquisar> ListarPesquisa = new ArrayList<Pesquisar>();
        ListarPesquisa = acesso.DetalhesdoPaciente(rg);
        codigopaciente = ListarPesquisa.get(0).getCodigo();
        jNome.setText(ListarPesquisa.get(0).getNome());
        jocupação.setText(ListarPesquisa.get(0).getOcupação());
        jpai.setText(ListarPesquisa.get(0).getPai());
        jMae.setText(ListarPesquisa.get(0).getMae());
        if (ListarPesquisa.get(0).getSexo() == 0) {
            jsexo.setSelectedIndex(1);//Masculino
        }
        if (ListarPesquisa.get(0).getSexo() == 1) {
            jsexo.setSelectedIndex(2);//Feminino
        }

        jrg.setText(ListarPesquisa.get(0).getRg());
        if (ListarPesquisa.get(0).getProcedencia() == 0) {
            jprocedencia.setSelectedIndex(0);
        }
        if (ListarPesquisa.get(0).getProcedencia() == 1) {
            //jprocedencia.setToolTipText("Zona Rural");
            jprocedencia.setSelectedIndex(1);
        }
        if (ListarPesquisa.get(0).getEstadoCivil() == 0) {
            jestadocivil.setSelectedIndex(0);//solteiro
        }
        if (ListarPesquisa.get(0).getEstadoCivil() == 1) {
            jestadocivil.setSelectedIndex(1);//casado
        }
        if (ListarPesquisa.get(0).getEstadoCivil() == 2) {
            jestadocivil.setSelectedIndex(2);//viuvo
        }
        if (ListarPesquisa.get(0).getEstadoCivil() == 3) {
            jestadocivil.setSelectedIndex(3);//Divorciado
        }
        jconjuge.setText(ListarPesquisa.get(0).getConjugue());
        jrua.setText(ListarPesquisa.get(0).getRua());
        jbairro.setText(ListarPesquisa.get(0).getBairro());
        jcidade.setText(ListarPesquisa.get(0).getCidade());
        jnumeroDoEndereco.setText(ListarPesquisa.get(0).getNumeroCasa());
        jcep.setText(ListarPesquisa.get(0).getCep());
        jtelefone.setText(ListarPesquisa.get(0).getTelefone());
        jTelefoneFixo.setText(ListarPesquisa.get(0).getTelefonefixo());
        jlistaNegraJustificativa.setText(ListarPesquisa.get(0).getMotivoListaNegra());
        if (ListarPesquisa.get(0).getPacienteAlta() == 0) {
//            jCPacieteComAlta.setSelected(false);
        }
        if (ListarPesquisa.get(0).getPacienteAlta() == 1) {
            //          jCPacieteComAlta.setSelected(true);
        }
        jnaturalidade.setText(ListarPesquisa.get(0).getNaturalidade());
        jnascimento.setText(ListarPesquisa.get(0).getDataNascimento());
        pacientelistaNegra = ListarPesquisa.get(0).getListaNegra();
        if (pacientelistaNegra == 1) {
            jNotificao.setText("Atenção! Paciente da Lista Negra.");
        }
        statusdotratamento = ListarPesquisa.get(0).getPacienteAlta();//se o valor for 0 (zero)significa que esta em tratamento
        if (statusdotratamento == 0) {
            jTratamento.setText("Em tratamento");
            jNovoTratamento.setEnabled(true);
        } else if (statusdotratamento == 1) {
            jTratamento.setText("Paciente com Alta");
            jButton1.setEnabled(false);
            jNovoTratamento.setVisible(true);
            jNovoTratamento.setEnabled(true);
        }
        if (pacientelistaNegra == 1) {
            jNotificao.setText("Atenção: Paciente da lista negra.");
            jRetiraListaNegra.setVisible(true);
        } else if (pacientelistaNegra == 0) {
            jRetiraListaNegra.setVisible(true);
            jRetiraListaNegra.setText("Colocar na lista Negra");
        }

    }

    private boolean VerificaCampos() {
        boolean retorno = true;
        if (jNome.getText().trim().equals("")) {
            retorno = false;
            jNome.setBorder(new LineBorder(Color.red));
        }
        if (jrg.getText().trim().equals("")) {
            retorno = false;
            jrg.setBorder(new LineBorder(Color.red));
        }
        if (jsexo.getSelectedIndex() == 0) {
            jsexo.setBorder(new LineBorder(Color.red));
            retorno = false;
        }

        return retorno;
    }

    private void BloqueiaCampos() {
        jNome.setBorder(null);
        jNome.setEditable(false);
        jNome.setBackground(Color.white);
        //-----------------
        jocupação.setBorder(null);
        jocupação.setEditable(false);
        jocupação.setBackground(Color.white);
        //------------------------------
        jpai.setBorder(null);
        jpai.setEditable(false);
        jpai.setBackground(Color.white);
        //------------------------------
        jMae.setBorder(null);
        jMae.setEditable(false);
        jMae.setBackground(Color.white);
        //------------------------------
        jsexo.setEnabled(false);
        jsexo.setBorder(null);
        jsexo.setBackground(Color.white);
        jsexo.setForeground(Color.black);
        //------------------------------
        jnascimento.setEditable(false);
        jnascimento.setBorder(null);
        jnascimento.setBackground(Color.white);
        //------------------------------
        jrua.setBorder(null);
        jrua.setEditable(false);
        jrua.setBackground(Color.white);
        //------------------------------
        jbairro.setEditable(false);
        jbairro.setBorder(null);
        jbairro.setBackground(Color.white);
        //------------------------------
        jrua.setBorder(null);
        jrua.setBackground(Color.white);
        //------------------------------
        jcidade.setBorder(null);
        jcidade.setEditable(false);
        jcidade.setBackground(Color.white);
        //------------------------------
        jnaturalidade.setBorder(null);
        jnaturalidade.setEditable(false);
        jnaturalidade.setBackground(Color.white);
        //------------------------------;
        jrg.setBorder(null);
        jrg.setEditable(false);
        jrg.setBackground(Color.white);
        //------------------------------
        jprocedencia.disable();
        jprocedencia.setBackground(Color.white);
        jprocedencia.setForeground(Color.black);
        //------------------------------
        jestadocivil.disable();
        jestadocivil.setBackground(Color.white);
        jestadocivil.setForeground(Color.BLACK);
        //------------------------------
        jconjuge.setBorder(null);
        jconjuge.setEditable(false);
        jconjuge.setBackground(Color.white);
        //------------------------------
        jnumeroDoEndereco.setEditable(false);
        jnumeroDoEndereco.setBorder(null);
        jnumeroDoEndereco.setBackground(Color.white);
        //------------------------------
        jcep.setBorder(null);
        jcep.setEditable(false);
        jcep.setBackground(Color.white);
        //------------------------------
        jTelefoneFixo.setBorder(null);
        jTelefoneFixo.setEditable(false);
        jTelefoneFixo.setBackground(Color.white);
        //------------------------------
        jtelefone.setBorder(null);
        jtelefone.setEditable(false);
        jtelefone.setBackground(Color.white);
        //------------------------------
        jlistaNegraJustificativa.setBorder(null);
        jlistaNegraJustificativa.setEditable(false);
        jlistaNegraJustificativa.setBackground(background);
        //------------------------------
//        jCPacieteComAlta.disable();
        //      jCPacieteComAlta.setBackground(Color.white);
        //------------------------------
        jBSalvar.setEnabled(false);
        jBSalvar.setBackground(Color.white);
        //------------------------------
    }

    private void AtivaCampos() {
        jNome.setBorder(new LineBorder(Color.blue));
        jNome.setEditable(true);
        jocupação.setBorder(new LineBorder(Color.blue));
        jocupação.setEditable(true);
        jpai.setBorder(new LineBorder(Color.blue));
        jpai.setEditable(true);
        jMae.setBorder(new LineBorder(Color.blue));
        jMae.setEditable(true);
        jsexo.setEnabled(true);
        jsexo.setBorder(new LineBorder(Color.blue));
        jnascimento.setEditable(true);
        jnascimento.setBorder(new LineBorder(Color.blue));
        jrua.setBorder(new LineBorder(Color.blue));
        jrua.setEditable(true);
        jbairro.setEditable(true);
        jbairro.setBorder(new LineBorder(Color.blue));
        jrua.setBorder(new LineBorder(Color.blue));
        jcidade.setBorder(new LineBorder(Color.blue));
        jcidade.setEditable(true);
        jnaturalidade.setBorder(new LineBorder(Color.blue));
        jnaturalidade.setEditable(true);
        jrg.setBorder(new LineBorder(Color.blue));
        jrg.setEditable(true);
        jprocedencia.enable(true);
        jestadocivil.enable(true);
        jconjuge.setBorder(new LineBorder(Color.blue));
        jconjuge.setEditable(true);
        jnumeroDoEndereco.setEditable(true);
        jnumeroDoEndereco.setBorder(new LineBorder(Color.blue));
        jcep.setBorder(new LineBorder(Color.blue));
        jcep.setEditable(true);
        jTelefoneFixo.setBorder(new LineBorder(Color.blue));
        jTelefoneFixo.setEditable(true);
        jtelefone.setBorder(new LineBorder(Color.blue));
        jtelefone.setEditable(true);
        jlistaNegraJustificativa.setBorder(new LineBorder(Color.blue));
        jlistaNegraJustificativa.setEditable(true);
        background = jlistaNegraJustificativa.getBackground();
        jlistaNegraJustificativa.setBackground(Color.WHITE);
        //jCPacieteComAlta.disable();
        jBSalvar.setEnabled(true);
        jlistaNegraJustificativa.setBackground(Color.WHITE);
    }

    private void SetValoresPaciente() {//Esta função será chamada se o usuario editar o cadastro, 
        //esta função seta os valores obtidos da interface para a classe de controle Paciente e de la grava no banco de dados
        sctp2.ClassesdeControle.Paciente acesso = new sctp2.ClassesdeControle.Paciente();
        acesso.setCodigo(codigopaciente);
        acesso.setNome(jNome.getText());
        acesso.setOcupacao(jocupação.getText());
        acesso.setPai(jpai.getText());
        acesso.setSexo((String) jsexo.getSelectedItem());
        acesso.setNascimento(jnascimento.getText());
        acesso.setRg(jrg.getText());
        acesso.setMae(jMae.getText());
        acesso.setProcedencia((String) jprocedencia.getSelectedItem());
        acesso.setEstadoCivil((String) jestadocivil.getSelectedItem());
        acesso.setConjuge(jconjuge.getText());
        acesso.setRua(jrua.getText());
        acesso.setBairro(jbairro.getText());
        acesso.setCidade(jcidade.getText());
        acesso.setNumeroEndereco(jnumeroDoEndereco.getText());
        acesso.setCep(jcep.getText());
        acesso.setTelefone(jtelefone.getText());
        acesso.setTelefoneFixo(jTelefoneFixo.getText());
        acesso.setListaNegraJustificativa(jlistaNegraJustificativa.getText());
        // acesso.setPacienteComAlta(jCPacieteComAlta.isSelected());
        acesso.setNaturalidade(jnaturalidade.getText());
        //-------------------------------------------
        if (jlistaNegraJustificativa.getText().equals("")) {//se a pessoa escrever algo na justificativa da lista negra significa que ela esta na lista negra, portanto setlistanega=1
            acesso.setListaNegra(0);
        } else {
            acesso.setListaNegra(1);//coloca a pessoa na lista negra
        }

    }

    private void PesquisaProntuario() throws ClassNotFoundException {
        sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
        ArrayList<PesquisarProntuarioStatico> ListarPesquisa = new ArrayList<PesquisarProntuarioStatico>();
        ListarPesquisa = acesso.PesquisarProntuariopelorg(jrg.getText());
        System.out.println("codigo rg" + jrg.getText());
        if (ListarPesquisa.size() == 0) {
            jNotificao.setText("Nenhum prontuário encontrado para este paciente!");
        } else {
            if (ListarPesquisa.get(0).getStatus().equals("Disponível")) {
                jsituacaoprontuario.setText("Disponível");
            }

            jprontuario.setText(Integer.toString(ListarPesquisa.get(0).getCodigoProntuario()));
            jresponsavelprontuario.setText(ListarPesquisa.get(0).getNome());
            jcelularprontuario.setText(ListarPesquisa.get(0).getTelefone());
            jtelefonfixoprontuario.setText(ListarPesquisa.get(0).getTelefoneFixo());
            jsituacaoprontuario.setText(ListarPesquisa.get(0).getStatus());//
            JdescricaoProntuario.setText(ListarPesquisa.get(0).getInformacoes());
        }

    }

    private void GravaTratamentoNoHistorico() throws ClassNotFoundException, SQLException {
        sctp2.BancodeDados.conexao acesso = new sctp2.BancodeDados.conexao();
        acesso.GravaPacienteNoHistorico(codigopaciente, jresponsavelprontuario.getText(), jrg.getText());
        jNotificao.setForeground(Color.blue);
        jNotificao.setText("O Histórico  já está disponível");
    }
}
