/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sctp2.Cadastros;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano
 */
public class Anamnese extends javax.swing.JFrame {

    /**
     * Creates new form Anamnese
     */
    public Anamnese() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        DesabilitaCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPrincipalQueixa = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jCSofredoenca = new javax.swing.JCheckBox();
        jCEmtratamentoMedico = new javax.swing.JCheckBox();
        jCUsodeMedicacao = new javax.swing.JCheckBox();
        jCPossuiAlergias = new javax.swing.JCheckBox();
        jCJafoiOperado = new javax.swing.JCheckBox();
        jCProblemasComHemorragia = new javax.swing.JCheckBox();
        jProblemasComCicatrizacao = new javax.swing.JCheckBox();
        jprobelmasComAnestesia = new javax.swing.JCheckBox();
        jgravidez = new javax.swing.JCheckBox();
        jTSofreAlgumaDoencaDescricao = new javax.swing.JTextField();
        jEmtratamentoMedicoDescricao = new javax.swing.JTextField();
        jUsodeMedicacaoDescricao = new javax.swing.JTextField();
        jPossuiAlergiaDescricao = new javax.swing.JTextField();
        jJaFoiOperadoDescricao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Anamnese");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Questionário de Saúde");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Principal queixa");

        jScrollPane1.setViewportView(jPrincipalQueixa);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Preencha no campos de texto a descrição do problema");

        jCSofredoenca.setText("Sofre alguma doença");
        jCSofredoenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCSofredoencaMouseClicked(evt);
            }
        });
        jCSofredoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSofredoencaActionPerformed(evt);
            }
        });

        jCEmtratamentoMedico.setText("Em tratamento médico");
        jCEmtratamentoMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCEmtratamentoMedicoMouseClicked(evt);
            }
        });
        jCEmtratamentoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEmtratamentoMedicoActionPerformed(evt);
            }
        });

        jCUsodeMedicacao.setText("Uso de alguma medicação?");
        jCUsodeMedicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCUsodeMedicacaoMouseClicked(evt);
            }
        });
        jCUsodeMedicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCUsodeMedicacaoActionPerformed(evt);
            }
        });

        jCPossuiAlergias.setText("Possui alergias?");
        jCPossuiAlergias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCPossuiAlergiasMouseClicked(evt);
            }
        });
        jCPossuiAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPossuiAlergiasActionPerformed(evt);
            }
        });

        jCJafoiOperado.setText("Já foi Operado?");
        jCJafoiOperado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCJafoiOperadoMouseClicked(evt);
            }
        });
        jCJafoiOperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCJafoiOperadoActionPerformed(evt);
            }
        });

        jCProblemasComHemorragia.setText("Problemas com Hemorragia");

        jProblemasComCicatrizacao.setText("Problemas com Cicatrização");

        jprobelmasComAnestesia.setText("Problemas com Anestesia");

        jgravidez.setText("gravidez");

        jTSofreAlgumaDoencaDescricao.setBackground(new java.awt.Color(204, 204, 204));

        jEmtratamentoMedicoDescricao.setBackground(new java.awt.Color(204, 204, 204));

        jUsodeMedicacaoDescricao.setBackground(new java.awt.Color(204, 204, 204));

        jPossuiAlergiaDescricao.setBackground(new java.awt.Color(204, 204, 204));

        jJaFoiOperadoDescricao.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCUsodeMedicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCSofredoenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCEmtratamentoMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCPossuiAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCJafoiOperado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jEmtratamentoMedicoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                    .addComponent(jTSofreAlgumaDoencaDescricao)
                                    .addComponent(jUsodeMedicacaoDescricao)
                                    .addComponent(jPossuiAlergiaDescricao)
                                    .addComponent(jJaFoiOperadoDescricao)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jprobelmasComAnestesia)
                            .addComponent(jCProblemasComHemorragia)
                            .addComponent(jgravidez)
                            .addComponent(jProblemasComCicatrizacao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCSofredoenca)
                            .addComponent(jTSofreAlgumaDoencaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProblemasComCicatrizacao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCEmtratamentoMedico)
                            .addComponent(jEmtratamentoMedicoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jgravidez))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsodeMedicacaoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCUsodeMedicacao)
                            .addComponent(jprobelmasComAnestesia))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPossuiAlergiaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCProblemasComHemorragia))
                            .addComponent(jCPossuiAlergias))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCJafoiOperado)
                            .addComponent(jJaFoiOperadoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<< Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Próxima etapa  >>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(405, 405, 405)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem2.setText("Voltar para o Início");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCUsodeMedicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCUsodeMedicacaoActionPerformed
        if (jCSofredoenca.isSelected() == true) {
            jTSofreAlgumaDoencaDescricao.enable();
            jTSofreAlgumaDoencaDescricao.setBackground(Color.white);
        }
        if (jCSofredoenca.isSelected() == false) {
            jTSofreAlgumaDoencaDescricao.disable();
            jTSofreAlgumaDoencaDescricao.setBackground(Color.GRAY);
        }


    }//GEN-LAST:event_jCUsodeMedicacaoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SetValoresAnamnese();//passa os valores para a classe Anamenese
        sctp2.Cadastros.DoencasSistemicas acesso = new sctp2.Cadastros.DoencasSistemicas();//chama a proxima tela
        this.setVisible(false);
        acesso.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sctp2.Cadastros.Paciente acesso = new sctp2.Cadastros.Paciente();
        this.setVisible(false);
        acesso.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int retorno;
        retorno = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja Cancelar este cadastro?");
        if (retorno == 0) {
            this.setVisible(false);
            sctp2.Principal.principal acesso = new sctp2.Principal.principal();
            acesso.setVisible(true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCSofredoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSofredoencaActionPerformed
        if (jCSofredoenca.isSelected() == true) {
            jTSofreAlgumaDoencaDescricao.enable();
            jTSofreAlgumaDoencaDescricao.setBackground(Color.white);
        }
        if (jCSofredoenca.isSelected() == false) {
            jTSofreAlgumaDoencaDescricao.disable();
            jTSofreAlgumaDoencaDescricao.setBackground(Color.GRAY);
        }

    }//GEN-LAST:event_jCSofredoencaActionPerformed

    private void jCSofredoencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCSofredoencaMouseClicked


    }//GEN-LAST:event_jCSofredoencaMouseClicked

    private void jCEmtratamentoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEmtratamentoMedicoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jCEmtratamentoMedicoActionPerformed

    private void jCPossuiAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPossuiAlergiasActionPerformed


    }//GEN-LAST:event_jCPossuiAlergiasActionPerformed

    private void jCJafoiOperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCJafoiOperadoActionPerformed

    }//GEN-LAST:event_jCJafoiOperadoActionPerformed

    private void jCJafoiOperadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCJafoiOperadoMouseClicked

        if (jCJafoiOperado.isSelected() == true) {
            jJaFoiOperadoDescricao.enable(true);
            jJaFoiOperadoDescricao.setBackground(Color.white);
        }
        if (jCJafoiOperado.isSelected() == false) {
            jJaFoiOperadoDescricao.disable();
            jJaFoiOperadoDescricao.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_jCJafoiOperadoMouseClicked

    private void jCPossuiAlergiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCPossuiAlergiasMouseClicked
        if (jCPossuiAlergias.isSelected() == true) {
            jPossuiAlergiaDescricao.enable(true);
            jPossuiAlergiaDescricao.setBackground(Color.white);
        }
        if (jCPossuiAlergias.isSelected() == false) {
            jPossuiAlergiaDescricao.disable();
            jPossuiAlergiaDescricao.setBackground(Color.GRAY);
    }//GEN-LAST:event_jCPossuiAlergiasMouseClicked
    }
    private void jCUsodeMedicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCUsodeMedicacaoMouseClicked
        if (jCUsodeMedicacao.isSelected() == true) {
            jUsodeMedicacaoDescricao.enable(true);
            jUsodeMedicacaoDescricao.setBackground(Color.white);
        }
        if (jCUsodeMedicacao.isSelected() == false) {
            jUsodeMedicacaoDescricao.disable();
            jUsodeMedicacaoDescricao.setBackground(Color.GRAY);
        }

    }//GEN-LAST:event_jCUsodeMedicacaoMouseClicked

    private void jCEmtratamentoMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCEmtratamentoMedicoMouseClicked
        if (jCEmtratamentoMedico.isSelected() == true) {
            jEmtratamentoMedicoDescricao.enable(true);
            jEmtratamentoMedicoDescricao.setBackground(Color.white);
        }
        if (jCEmtratamentoMedico.isSelected() == false) {
            jEmtratamentoMedicoDescricao.disable();
            jEmtratamentoMedicoDescricao.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_jCEmtratamentoMedicoMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      this.setVisible(false);
      sctp2.Principal.principal acesso= new sctp2.Principal.principal();
      acesso.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anamnese().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCEmtratamentoMedico;
    private javax.swing.JCheckBox jCJafoiOperado;
    private javax.swing.JCheckBox jCPossuiAlergias;
    private javax.swing.JCheckBox jCProblemasComHemorragia;
    private javax.swing.JCheckBox jCSofredoenca;
    private javax.swing.JCheckBox jCUsodeMedicacao;
    private javax.swing.JTextField jEmtratamentoMedicoDescricao;
    private javax.swing.JTextField jJaFoiOperadoDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPossuiAlergiaDescricao;
    private javax.swing.JTextPane jPrincipalQueixa;
    private javax.swing.JCheckBox jProblemasComCicatrizacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTSofreAlgumaDoencaDescricao;
    private javax.swing.JTextField jUsodeMedicacaoDescricao;
    private javax.swing.JCheckBox jgravidez;
    private javax.swing.JCheckBox jprobelmasComAnestesia;
    // End of variables declaration//GEN-END:variables

    private void SetValoresAnamnese() {
        sctp2.ClassesdeControle.Anamnese acesso = new sctp2.ClassesdeControle.Anamnese();
        acesso.setPrincipalQueixa(jPrincipalQueixa.getText());
        acesso.setSofreAlgumaDoenca(jCSofredoenca.isSelected());
        acesso.setEmTratamentoMedico(jCEmtratamentoMedico.isSelected());
        acesso.setEmTratamentoMedicoDescricao(jEmtratamentoMedicoDescricao.getText());
        acesso.setUsoDeAlgumaMedicacao(jCUsodeMedicacao.isSelected());
        acesso.setUsoDeAlgumaMedicacaoDescricao(jUsodeMedicacaoDescricao.getText());
        acesso.setPossuiAlergias(jCPossuiAlergias.isSelected());
        acesso.setPossuiAlergiasDescricao(jPossuiAlergiaDescricao.getText());
        acesso.setJaFoiOperado(jCJafoiOperado.isSelected());
        acesso.setJaFoiOperadoDescricao(jJaFoiOperadoDescricao.getText());
        acesso.setProblemasComHemorragia(jProblemasComCicatrizacao.isSelected());
        acesso.setProblemasComHemorragia(jCProblemasComHemorragia.isSelected());
        //acesso.setProblemasComHemorragiaDescricao(jProblemasComHemorragiaDescricao.getText());
        acesso.setProblemasComCicatrizacao(jProblemasComCicatrizacao.isSelected());
        acesso.setGravidez(jgravidez.isSelected());
        acesso.setProblemasComAnestesia(jprobelmasComAnestesia.isSelected());
    }

    private void DesabilitaCampos() {
        jJaFoiOperadoDescricao.disable();
        jPossuiAlergiaDescricao.disable();
        jUsodeMedicacaoDescricao.disable();
        jEmtratamentoMedicoDescricao.disable();
        jTSofreAlgumaDoencaDescricao.disable();
    }

    private void HabilitaCampos() {//Esta função habilita todos os campos textfield da interface Anamnese
        jJaFoiOperadoDescricao.enable(true);
        jJaFoiOperadoDescricao.setBackground(Color.white);
        jPossuiAlergiaDescricao.enable(true);
        jPossuiAlergiaDescricao.setBackground(Color.white);
        jUsodeMedicacaoDescricao.enable(true);
        jUsodeMedicacaoDescricao.setBackground(Color.white);
        jEmtratamentoMedicoDescricao.enable(true);
        jEmtratamentoMedicoDescricao.setBackground(Color.white);
        jTSofreAlgumaDoencaDescricao.enable();
        jTSofreAlgumaDoencaDescricao.setBackground(Color.white);
    }
}
