/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sctp2.NovoTratamento;

import sctp2.Cadastros.*;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.shape.Line;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sctp2.Pesquisar.Pesquisar;

/**
 *
 * @author Adriano
 */
public class CadastroResponsavel extends javax.swing.JFrame  {
private int idDoResponsavel=-1;//esta variavel servirar para determinar se é um novo cadastro é ou uma atualização de cadastro existente
private int tamanhoFonte=15;//DEFINE O TAMANHO DA FONTE DESTA TELA
    /**
     * Creates new form CadastroResponsavel
     * 
     */
    public CadastroResponsavel() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        jEditar.disable();
        jExcluir.disable();
        jNovoResponsavel.disable();
        jEditar.setVisible(false);
        jExcluir.setVisible(false);
        jNovoResponsavel.setVisible(false);
        jnotificacao2.setText("Cadastrar um novo responsável!");    
         TamanhoDaFonte(tamanhoFonte);//função que aumenta/diminui o tamanho da fonte da tela
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBDiminuiTamFOnte = new javax.swing.JButton();
        jBAumentaTamFOnte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPesquisa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNotificacao = new javax.swing.JTextField();
        jID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jNovoResponsavel = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jFTelefoneFixo = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFTelefoneCelular = new javax.swing.JFormattedTextField();
        nomeresponsavel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jnotificacao2 = new javax.swing.JTextField();
        jinformacaodoconteine = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de responsavel");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jSalvar.setForeground(new java.awt.Color(0, 51, 255));
        jSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save2.png"))); // NOI18N
        jSalvar.setText("Salvar");
        jSalvar.setBorder(null);
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left-arrow.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBDiminuiTamFOnte.setBackground(new java.awt.Color(255, 255, 255));
        jBDiminuiTamFOnte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1467516016_icon-113-search-minus.png"))); // NOI18N
        jBDiminuiTamFOnte.setBorder(null);
        jBDiminuiTamFOnte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiminuiTamFOnteActionPerformed(evt);
            }
        });

        jBAumentaTamFOnte.setBackground(new java.awt.Color(255, 255, 255));
        jBAumentaTamFOnte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1467515709_icon-112-search-plus.png"))); // NOI18N
        jBAumentaTamFOnte.setBorder(null);
        jBAumentaTamFOnte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAumentaTamFOnteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jBAumentaTamFOnte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBDiminuiTamFOnte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDiminuiTamFOnte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAumentaTamFOnte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastre um novo aluno responsável por prontuários");

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPesquisa.setText("Pesquisar responsável");
        jPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPesquisaMouseClicked(evt);
            }
        });
        jPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisaActionPerformed(evt);
            }
        });
        jPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPesquisaKeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search3.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aluno/Responsavel pelo prontuário");

        jNotificacao.setEditable(false);
        jNotificacao.setBackground(new java.awt.Color(255, 255, 255));
        jNotificacao.setForeground(java.awt.Color.red);
        jNotificacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNotificacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jID.setEditable(false);
        jID.setForeground(new java.awt.Color(255, 255, 255));
        jID.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jNovoResponsavel.setBackground(new java.awt.Color(255, 255, 255));
        jNovoResponsavel.setForeground(new java.awt.Color(0, 51, 255));
        jNovoResponsavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo contato pequeno.png"))); // NOI18N
        jNovoResponsavel.setText("Novo responsável");
        jNovoResponsavel.setToolTipText("Cadastre um novo responsável");
        jNovoResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoResponsavelActionPerformed(evt);
            }
        });

        jExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jExcluir.setForeground(new java.awt.Color(0, 51, 255));
        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir pequeno.png"))); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jEditar.setBackground(new java.awt.Color(255, 255, 255));
        jEditar.setForeground(new java.awt.Color(0, 51, 255));
        jEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar pqno.png"))); // NOI18N
        jEditar.setText("Editar");
        jEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });

        jFTelefoneFixo.setEditable(false);
        try {
            jFTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefoneFixo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTelefoneFixo.setToolTipText("Digite o número de celular incluindo o nono dígito");
        jFTelefoneFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTelefoneFixoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Telefone Fixo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Telefone Celular:  ");

        jFTelefoneCelular.setBackground(new java.awt.Color(240, 240, 240));
        try {
            jFTelefoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefoneCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nomeresponsavel.setBackground(new java.awt.Color(240, 240, 240));
        nomeresponsavel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nome do responsável: ");

        jnotificacao2.setBackground(new java.awt.Color(240, 240, 240));
        jnotificacao2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jnotificacao2.setForeground(java.awt.Color.blue);
        jnotificacao2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jnotificacao2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jinformacaodoconteine.setBackground(new java.awt.Color(51, 51, 255));
        jinformacaodoconteine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jinformacaodoconteine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jnotificacao2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jinformacaodoconteine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNovoResponsavel)))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jnotificacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jinformacaodoconteine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExcluir)
                    .addComponent(jNovoResponsavel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(jNotificacao))
                        .addGap(0, 0, 0)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/detalhes.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/house pequena.png"))); // NOI18N
        jMenuItem2.setText("Menu Principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        boolean retorno = false;
        if (nomeresponsavel.getText().trim().equals("")) {
            nomeresponsavel.setBorder(new LineBorder(Color.red));
            jnotificacao2.setForeground(Color.red);
            jnotificacao2.setText("O campo Nome está vazio!");
        } else {
            PassaValoresResponsavel();//passa os valore para classe de responsavel
            sctp2.ClassesdeControle.Controle acesso = new sctp2.ClassesdeControle.Controle();
            if (idDoResponsavel != -1) {
                try {
                    acesso.AtualizaResponsavelProntuario();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
                }

                LimpaTela();//restaura valor padrao da variavel
            } else {
                if (idDoResponsavel == -1) {
                    try {
                        acesso.GravaResponsavelProntuario();
                        LimpaTela();//restaura valor padrao da variavel
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (retorno == false) {

                    }
                }
            }
        }
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int retorno;
        retorno = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar o cadastro?");
        if (retorno == 0) {
            this.setVisible(false);
            sctp2.Principal.principal mostratelaprincipal = new sctp2.Principal.principal();
            mostratelaprincipal.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFTelefoneFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTelefoneFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTelefoneFixoActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPesquisaMouseClicked
        jPesquisa.setText("");//limpa o campo de pesquisa
    }//GEN-LAST:event_jPesquisaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            EfetuaPesquisa();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisaActionPerformed
        try {
            EfetuaPesquisa();        // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPesquisaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPesquisaKeyTyped
if(jPesquisa.getText().equals("Pesquisar responsável"))jPesquisa.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisaKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //quando o usuario clicar em um dos nomes da tabela, ela irá seta seus detalhes nos campos de nome, telefone e fixo
        int linha = jTable1.getSelectedRow();
        Object valor = null;//valor recebera o valor da celular da tabela
        valor = jTable1.getValueAt(linha, 0);
        sctp2.BancodeDados.ConexaoPacotePesquisar acesso = new sctp2.BancodeDados.ConexaoPacotePesquisar();
        ArrayList<Pesquisar> listaPesquisa;//array pra pegar o resultado da pesquisa
        try {
            listaPesquisa = acesso.PesquisarProntuarioPacienteDetalhes((String) valor);
            nomeresponsavel.setText(listaPesquisa.get(0).getNome());
            jFTelefoneCelular.setText(listaPesquisa.get(0).getTelefone());
            jFTelefoneFixo.setText(listaPesquisa.get(0).getTelefonefixo());
            idDoResponsavel = (listaPesquisa.get(0).getCodigo());
            jnotificacao2.setText("Atualizar Dados.");
            BloqueiaCampos(false);//impedir que o usuario altere os campos
            jinformacaodoconteine.setText("Clique no botão Editar para alterar os dados!");
            jEditar.enable(true);//ativa o botao de editar
            jExcluir.enable(true);//ativa o botao de excluir
            jNovoResponsavel.enable(true);//ativa o botao novo responsavel
            jEditar.setVisible(true);
            jExcluir.setVisible(true);
            jNovoResponsavel.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
        BloqueiaCampos(true);        // TODO add your handling code here:
        nomeresponsavel.setBorder(new LineBorder(Color.black));
        jFTelefoneCelular.setBorder(new LineBorder(Color.black));
        jFTelefoneFixo.setBorder(new LineBorder(Color.black));
        jLabel6.setText("Para Salvar clique no botão na faixa azul.");
        
    }//GEN-LAST:event_jEditarActionPerformed

    private void jNovoResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoResponsavelActionPerformed
        LimpaTela();
        BloqueiaCampos(true);
        jEditar.enable(false);
        jEditar.setVisible(false);
        jExcluir.enable(false);
        jExcluir.setVisible(false);
        jNovoResponsavel.enable(false);
        jNovoResponsavel.setVisible(false);

    }//GEN-LAST:event_jNovoResponsavelActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
    try {
        ExcluiResponsável();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(CadastroResponsavel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBDiminuiTamFOnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiminuiTamFOnteActionPerformed
        TamanhoDaFonte(tamanhoFonte-1);        // TODO add your handling code here:
    }//GEN-LAST:event_jBDiminuiTamFOnteActionPerformed

    private void jBAumentaTamFOnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAumentaTamFOnteActionPerformed
        TamanhoDaFonte(tamanhoFonte+1);        // TODO add your handling code here:
    }//GEN-LAST:event_jBAumentaTamFOnteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroResponsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroResponsavel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAumentaTamFOnte;
    private javax.swing.JButton jBDiminuiTamFOnte;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jEditar;
    private javax.swing.JButton jExcluir;
    private javax.swing.JFormattedTextField jFTelefoneCelular;
    private javax.swing.JFormattedTextField jFTelefoneFixo;
    private javax.swing.JTextField jID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNotificacao;
    private javax.swing.JButton jNovoResponsavel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPesquisa;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jinformacaodoconteine;
    private javax.swing.JTextField jnotificacao2;
    private javax.swing.JTextField nomeresponsavel;
    // End of variables declaration//GEN-END:variables

    private void PassaValoresResponsavel() {//os nomes contindos no campos preenchidos sao passados para a classe responsavelprontuario
        sctp2.ClassesdeControle.responsavelprontuario acesso = new sctp2.ClassesdeControle.responsavelprontuario();
        acesso.setNomeresponsavel(nomeresponsavel.getText());
        acesso.setTelefoneCelular(jFTelefoneCelular.getText());
        acesso.setTelefoneFixo(jFTelefoneFixo.getText());
        acesso.setIdResponsavel(idDoResponsavel);
    }

    private void EfetuaPesquisa() throws ClassNotFoundException {//Esta função faza a pesquisa e popula a tabela com os nomes encontrados
        sctp2.BancodeDados.ConexaoPacotePesquisar acesso = new sctp2.BancodeDados.ConexaoPacotePesquisar();
        ArrayList<Pesquisar> listaPesquisa;//array pra pegar o resultado da pesquisa
        DefaultTableModel valor = (DefaultTableModel) jTable1.getModel();//criando a chave valor para o objeto tabela
        listaPesquisa = acesso.PesquisarResponsavelProntuario(jPesquisa.getText(),1);// o valor 1 define o tipo de pesquisa
        LimpaTela();
        if (listaPesquisa.size() == 0) {
            jNotificacao.setText("Sem resultados");
        } else {

            for (int i = 0; i < listaPesquisa.size(); i++) {
                System.out.println("::" + listaPesquisa.get(i).getNome());
                valor.addRow(new String[]{Integer.toString(listaPesquisa.get(i).getCodigo()), listaPesquisa.get(i).getNome()});
                BloqueiaCampos(false);//esta função bloqueia os campos para impedir a edição das informações
                jNotificacao.setForeground(Color.blue);
                jNotificacao.setText("Clique no nome para ver seus detalhes!");
            }
        }
    }

    private void LimpaTela() {
        //limpa todos os campos
        jTable1.setSelectionBackground(Color.BLUE);//defini a cor de seleção da tabela para azul
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        //********************************************
        nomeresponsavel.setText("");
        jFTelefoneCelular.setText("");
        jFTelefoneFixo.setText("");
        jnotificacao2.setText("");
        jnotificacao2.setForeground(Color.blue);
        nomeresponsavel.setBorder(new LineBorder(Color.gray));
        jLabel6.setText("");
        jEditar.disable();
        jExcluir.disable();
        jNovoResponsavel.disable();
        idDoResponsavel = -1;//valor padrão da variavel
        BloqueiaCampos(false);//bloqueia os botoes editar excluir
        nomeresponsavel.setBackground(Color.white);
            jFTelefoneCelular.setBackground(Color.white);
            jFTelefoneFixo.setBackground(Color.white);
            jinformacaodoconteine.setText("");
    }

    private void BloqueiaCampos(boolean status) {
        if (status == false) {
            nomeresponsavel.setEditable(false);
            jFTelefoneCelular.setEditable(false);
            jFTelefoneFixo.setEditable(false);
            //nomeresponsavel.setBackground(Color.WHITE);
            //jFTelefoneCelular.setBackground(Color.white);
            //jFTelefoneFixo.setBackground(Color.white);
            nomeresponsavel.setBorder(null);
            jFTelefoneCelular.setBorder(null);
            jFTelefoneFixo.setBorder(null);
            jEditar.enable(false);
            jExcluir.enable(false);
            jNovoResponsavel.enable(false);

            //------------------------------------
        } else
            if (status == true) {
                nomeresponsavel.setEditable(true);
                jFTelefoneCelular.setEditable(true);
                jFTelefoneFixo.setEditable(true);
                nomeresponsavel.setBackground(Color.white);
                jFTelefoneCelular.setBackground(Color.white);
                jFTelefoneFixo.setBackground(Color.white);
               

    
//------------------------------------
    
    
    }
    
    
    }

    private void ExcluiResponsável() throws ClassNotFoundException {
        int resultado;
        resultado=JOptionPane.showConfirmDialog(rootPane, "Se você excluir este responsável, ele será desvinculado de todos os prontuários.");
        if(resultado==0){
            sctp2.BancodeDados.conexao acesso= new sctp2.BancodeDados.conexao();
            acesso.ExcluiresponsavelProntuario(idDoResponsavel);
            LimpaTela();
            
        }
        else
            if(resultado==1)System.out.println("não excluindo....");
        else
            if(resultado==2)System.out.println("cancelando....");
    
    }

    private void TamanhoDaFonte(int tamanhoFonte) {
            this.tamanhoFonte=tamanhoFonte;
        System.out.println("tam "+tamanhoFonte);
        if((this.tamanhoFonte<24) && (this.tamanhoFonte>15)){
            jBDiminuiTamFOnte.setEnabled(true);
        jBAumentaTamFOnte.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jButton2.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jButton3.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel3.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel2.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jEditar.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jExcluir.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jFTelefoneCelular.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jFTelefoneFixo.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jnotificacao2.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jNovoResponsavel.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jNotificacao.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        
        jLabel2.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel3.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel4.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel5.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        jLabel6.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        nomeresponsavel.setFont(new Font("Times new Roman", Font.BOLD, tamanhoFonte));
        }
          else
            if(this.tamanhoFonte>=24){
                jBAumentaTamFOnte.setEnabled(false);
                jBDiminuiTamFOnte.setEnabled(true);
                
            }
        else
        if(this.tamanhoFonte<=15){
                jBDiminuiTamFOnte.setEnabled(false);
                jBAumentaTamFOnte.setEnabled(true);
                }
    }
}
