/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sctp2.Prontuarios;

import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sctp2.BancodeDados.ConexaoPacotePesquisar;
import sctp2.Pesquisar.PesquisarProntuario;

/**
 *
 * @author Adriano
 */
public class Prontuario extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarProntuarioEmprestado
     */
    private int reservarOuEmprestrar;//Esta variavel define se vc esta emprestando(1) ou reservando(2) para alguem um prontuario
    ArrayList<PesquisarProntuario> ListarPesquisa;

    public Prontuario() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        jBprontuario.setEnabled(false);
        jReservaProntuario.setEnabled(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(true);
        jPanel3.setVisible(false);
        jCancelarReserva.setVisible(false);

    }

    public Prontuario(String id) throws ClassNotFoundException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//inicia a janela maximizada
        jBprontuario.setEnabled(false);
        jPanel4.setVisible(false);
        jProntuario.setText(id);
        Pesquisar();
        jPanel3.setVisible(true);
        jPanel3.setVisible(false);
        jCancelarReserva.setVisible(false);
    }

    /**
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProntuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTNotificacao = new javax.swing.JTextField();
        jBprontuario = new javax.swing.JButton();
        jReservaProntuario = new javax.swing.JButton();
        jPanel4 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        NomeresponsavelProntuario = new javax.swing.JTextField();
        jCodigoResponsavel = new javax.swing.JTextField();
        JcelularoAluno = new javax.swing.JTextField();
        jTelefoneFixo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jNomeProfessor = new javax.swing.JTextField();
        jTelefoneFixoProfessor = new javax.swing.JTextField();
        jCelularProfessor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jDateEmprestimoInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateEmprestimoFim = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jNotificacao = new javax.swing.JTextField();
        jDetalhesProntuario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescricaoProntuario = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTNprontuario = new javax.swing.JTextField();
        jTPaciente = new javax.swing.JTextField();
        jLStatus = new javax.swing.JLabel();
        jCancelarReserva = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar Prontuario Emprestado");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left-arrow.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clipboard.png"))); // NOI18N
        jButton5.setText("Ver Prontuários por Aluno");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prontuários");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite o numero do prontuario: ");

        jProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProntuarioActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prontuario", "Responsavel", "Celular", "Tel Fixo", "Paciente", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jTNotificacao.setEditable(false);
        jTNotificacao.setBackground(new java.awt.Color(255, 255, 255));
        jTNotificacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTNotificacao.setForeground(new java.awt.Color(0, 0, 255));
        jTNotificacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNotificacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jBprontuario.setBackground(new java.awt.Color(255, 255, 255));
        jBprontuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBprontuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ExclamationMark.png"))); // NOI18N
        jBprontuario.setText("Receber Prontuario");
        jBprontuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jBprontuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprontuarioActionPerformed(evt);
            }
        });

        jReservaProntuario.setBackground(new java.awt.Color(255, 255, 255));
        jReservaProntuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jReservaProntuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/keep.png"))); // NOI18N
        jReservaProntuario.setText("Reservar ");
        jReservaProntuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jReservaProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReservaProntuarioActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(240, 240, 240));
        label1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 102, 255));
        label1.setName(""); // NOI18N
        label1.setText("Você está emprestando o prontuário para:");

        label2.setBackground(new java.awt.Color(240, 240, 240));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Responsável:");

        NomeresponsavelProntuario.setEditable(false);

        jCodigoResponsavel.setEditable(false);

        JcelularoAluno.setEditable(false);

        jTelefoneFixo.setEditable(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Professor/Orientador");

        jNomeProfessor.setEditable(false);

        jTelefoneFixoProfessor.setEditable(false);

        jCelularProfessor.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCodigoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JcelularoAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(jTelefoneFixo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNomeProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTelefoneFixoProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCelularProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeresponsavelProntuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodigoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeresponsavelProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JcelularoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTelefoneFixoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCelularProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Período:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("a");

        jDateEmprestimoFim.setDateFormatString("dd/MM/yyyy");
        jDateEmprestimoFim.setMinSelectableDate(new java.util.Date(-62135755121000L));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fim.png"))); // NOI18N
        jButton3.setText("Confirmar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1473476015_Close_Icon.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateEmprestimoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateEmprestimoFim, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateEmprestimoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jDateEmprestimoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jNotificacao.setEditable(false);
        jNotificacao.setBackground(new java.awt.Color(255, 255, 255));
        jNotificacao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jNotificacao.setForeground(new java.awt.Color(204, 0, 0));
        jNotificacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jDetalhesProntuario.setBackground(new java.awt.Color(255, 255, 255));
        jDetalhesProntuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Descrição do Prontuário: ");

        jDescricaoProntuario.setEditable(false);
        jDescricaoProntuario.setColumns(20);
        jDescricaoProntuario.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jDescricaoProntuario.setRows(5);
        jScrollPane2.setViewportView(jDescricaoProntuario);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Prontuário: ");

        jTNprontuario.setEditable(false);

        jTPaciente.setEditable(false);

        javax.swing.GroupLayout jDetalhesProntuarioLayout = new javax.swing.GroupLayout(jDetalhesProntuario);
        jDetalhesProntuario.setLayout(jDetalhesProntuarioLayout);
        jDetalhesProntuarioLayout.setHorizontalGroup(
            jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalhesProntuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDetalhesProntuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDetalhesProntuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDetalhesProntuarioLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        jDetalhesProntuarioLayout.setVerticalGroup(
            jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDetalhesProntuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDetalhesProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addComponent(jTPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jCancelarReserva.setBackground(new java.awt.Color(255, 204, 204));
        jCancelarReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCancelarReserva.setForeground(new java.awt.Color(153, 0, 51));
        jCancelarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/black_Cancel.png"))); // NOI18N
        jCancelarReserva.setText("Cancelar Reserva");
        jCancelarReserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTNotificacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jReservaProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                            .addComponent(jDetalhesProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBprontuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jReservaProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCancelarReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDetalhesProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/detalhes.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dente branco.png"))); // NOI18N
        jMenuItem1.setText("Menu Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1473476015_Close_Icon.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new sctp2.Principal.principal().setVisible(true);   //sctp2.Principal.principal acesso
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            LimpaTabela();
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
            Pesquisar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProntuarioActionPerformed
        try {
            LimpaTabela();
            Pesquisar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jProntuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        sctp2.Principal.principal acesso = new sctp2.Principal.principal();
        acesso.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBprontuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprontuarioActionPerformed
        //se o prontuario estiver emprestado este botao irpa recebê-lo, se for o contrário ele irá emprestalo
        if ("Emprestado".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 5))) {
            String id = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);//pega o numero do prontuario
            sctp2.BancodeDados.ConexaoPacotePesquisar acesso = new sctp2.BancodeDados.ConexaoPacotePesquisar();//chave de acesso a função de pesquisa
            boolean retorno = false;
            try {
                retorno = acesso.AtualizaStatusProntuario(id);//recebe o prontuario
                if (retorno == true) {
                    LimpaTabela();
                    jPanel3.setVisible(false);
                    jPanel4.setVisible(false);
                    Pesquisar();
                    jTNotificacao.setText("O prontuário foi recebido com sucesso!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//fim do if de emprestado
        else if ("Disponível".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 5))) {
            try {
                new sctp2.Prontuarios.ResponsavelProntuario(1, jProntuario.getText()).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);

        } else {
            if ("Reservado".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 5))) {
                try {
                    new sctp2.Prontuarios.ResponsavelProntuario(1, jProntuario.getText()).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);

            } else {
                jBprontuario.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBprontuarioActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        MostraDetalhesProntuario();
        jBprontuario.setEnabled(true);        // TODO add your handling code here:
        jTable1.setSelectionForeground(Color.lightGray);
        if ("Disponível".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 5))) {
            jReservaProntuario.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jBprontuario.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void jReservaProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReservaProntuarioActionPerformed

        if ("Disponível".equals(jTable1.getValueAt(jTable1.getSelectedRow(), 5))) {
            try {
                new sctp2.Prontuarios.ResponsavelProntuario(2, jProntuario.getText()).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);

        } else {
            jReservaProntuario.setEnabled(false);
        }
    }//GEN-LAST:event_jReservaProntuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
ConexaoPacotePesquisar acesso = new ConexaoPacotePesquisar();
        LocalDate data1 = null ,data2;
if(VerificaCampoDataVazia());
else
    if(ComparaDataInicialComDataFinal(ConverteDataBD(jDateEmprestimoInicio.getDate()),ConverteDataBD(jDateEmprestimoFim.getDate()))==true)jNotificacao.setText("A data Final deve ser maior do que a data inicial!");
else
        if (((ComparaData((ConverteDataBD(jDateEmprestimoInicio.getDate()))))||(ComparaData(ConverteDataBD(jDateEmprestimoFim.getDate()))))==true)jNotificacao.setText("A data de Emprestimo ou devolução é anterior ao dia de hoje!");
else
            if(this.reservarOuEmprestrar==1){//Emprestar prontuário
        if(ListarPesquisa.get(0).getStatus().equals("Disponível")){
            boolean retorno;
            try {
                retorno = acesso.EmprestaProntuario(jProntuario.getText(), jCodigoResponsavel.getText(), Date.valueOf(ConverteDataBD(jDateEmprestimoInicio.getDate())), Date.valueOf(ConverteDataBD(jDateEmprestimoFim.getDate())));
                if (retorno == true) {
                        jButton3.setEnabled(false);
                        jButton4.setText("Ocultar");
                        LimpaTabela();
                        Pesquisar();
                        jNotificacao.setText("Prontuário Emprestado");
                    }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            }
    
}//fim da condição prontuário disponível
            if(ListarPesquisa.get(0).getStatus().equals("Reservado")){
                System.out.println("reservado");
        //Verificar Se o responsável a ser emprestado é o mesmo que está reservado
       if((Integer.parseInt(jCodigoResponsavel.getText())!=ListarPesquisa.get(0).getIdUsuarioReservado())&&(ComparaData(ConverteDataBD(jDateEmprestimoFim.getDate())))==false){
        
         JOptionPane.showMessageDialog(rootPane,"Você está tentando emprestar um prontuário reservado para uma pessoa diferente da qual ele foi reservado, caso deseje realmente continuar, cancele a reserva antes! ");
         jCancelarReserva.setVisible(true);
         }
        else
        {
            boolean retorno;
            try {
                retorno = acesso.EmprestaProntuario(jProntuario.getText(), jCodigoResponsavel.getText(), Date.valueOf(ConverteDataBD(jDateEmprestimoInicio.getDate())), Date.valueOf(ConverteDataBD(jDateEmprestimoFim.getDate())));
                if (retorno == true) {
                        jButton3.setEnabled(false);
                        jButton4.setText("Ocultar");
                        LimpaTabela();
                        Pesquisar();
                        jNotificacao.setText("Prontuário Emprestado");
                    }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
           
                
        
    }//fim da condição reservado
            }
            else if(this.reservarOuEmprestrar==2){
                try {
                   boolean retorno = acesso.ReservarProntuario(jProntuario.getText(), jCodigoResponsavel.getText(), Date.valueOf(ConverteDataBD(jDateEmprestimoInicio.getDate())), Date.valueOf(ConverteDataBD(jDateEmprestimoFim.getDate())));
                    if (retorno) {
                        jButton3.setEnabled(false);
                        jButton4.setText("Ocultar");
                        LimpaTabela();
                        Pesquisar();
                        jNotificacao.setText("Prontuario Reservado");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jCancelarReserva.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarReservaActionPerformed
int resposta=JOptionPane.showConfirmDialog(rootPane,"você deseja realmente cancelar esta reserva?");
if(resposta==0){
    ConexaoPacotePesquisar acesso = new ConexaoPacotePesquisar();
    int retorno;
    try {
        
        retorno = acesso.CancelaReservaProntuario(ListarPesquisa.get(0).getCodigoProntuario());
        if (retorno ==1) {
                        jCancelarReserva.setEnabled(false);
                        jButton4.setText("Ocultar");
                        LimpaTabela();
                        Pesquisar();
                        jNotificacao.setText("Reserva cancelada com sucesso!");
                        jCancelarReserva.setVisible(false);
                    }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar cancelar a reserva, se o erro persistir peça ajuda ao Programador!.");
            jNotificacao.setText("Não foi possível cancelar a reserva!");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Prontuario.class.getName()).log(Level.SEVERE, null, ex);
    }
                    }

    
    }//GEN-LAST:event_jCancelarReservaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new sctp2.Prontuarios.ProntuarioPorResponsavel().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prontuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prontuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JcelularoAluno;
    private javax.swing.JTextField NomeresponsavelProntuario;
    private javax.swing.JButton jBprontuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jCancelarReserva;
    private javax.swing.JTextField jCelularProfessor;
    private javax.swing.JTextField jCodigoResponsavel;
    private com.toedter.calendar.JDateChooser jDateEmprestimoFim;
    private com.toedter.calendar.JDateChooser jDateEmprestimoInicio;
    private javax.swing.JTextArea jDescricaoProntuario;
    private javax.swing.JPanel jDetalhesProntuario;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jNomeProfessor;
    private javax.swing.JTextField jNotificacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Panel jPanel4;
    private javax.swing.JTextField jProntuario;
    private javax.swing.JButton jReservaProntuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTNotificacao;
    private javax.swing.JTextField jTNprontuario;
    private javax.swing.JTextField jTPaciente;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTelefoneFixo;
    private javax.swing.JTextField jTelefoneFixoProfessor;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

    private void Pesquisar() throws ClassNotFoundException {
        sctp2.BancodeDados.ConexaoPacotePesquisar acesso = new sctp2.BancodeDados.ConexaoPacotePesquisar();
        DefaultTableModel valor = (DefaultTableModel) jTable1.getModel();//criando a chave valor para o objeto tabela
        ListarPesquisa = new ArrayList<PesquisarProntuario>();
        jBprontuario.setEnabled(false);//desativa o botao de emprestar/receber
        ListarPesquisa = acesso.PesquisarProntuario(jProntuario.getText());
        if (ListarPesquisa.size() == 0) {
            jTNotificacao.setForeground(Color.red);
            jTNotificacao.setText("Nenhum prontuário encontrado!");
        } else {
            if (ListarPesquisa.get(0).getStatus().equals("Disponível")) {
                jBprontuario.setText("Emprestar Prontuário");
            }
            if (ListarPesquisa.get(0).getStatus().equals("Emprestado")) {
                jBprontuario.setText("Receber Prontuário");
            }
            if (ListarPesquisa.get(0).getStatus().equals("Reservado")) {
                jBprontuario.setText("Emprestar Prontuário");
            }
            for (int i = 0; i < ListarPesquisa.size(); i++) {
                valor.addRow((new String[]{(ListarPesquisa.get(i).getProntuario()), ListarPesquisa.get(i).getNome(), ListarPesquisa.get(i).getTelefone(), ListarPesquisa.get(i).getTelefoneFixo(), ListarPesquisa.get(i).getPaciente(), ListarPesquisa.get(i).getStatus()}));//
                jTNotificacao.setForeground(Color.BLUE);
                jTNotificacao.setText("Selecione o prontuario para emprestar ou devolvê-lo.");
            }
        }

    }

    private void LimpaTabela() {
        //limpa pesquisas existentes
        jTable1.setSelectionBackground(Color.BLUE);//defini a cor de seleção da tabela para azul
        DefaultTableModel tabela;
        tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setNumRows(0);
        jNotificacao.setText("");
        jPanel3.setEnabled(false);
        jPanel4.setEnabled(false);
        //********************************************
    }

    public void Recebe(String codigo, String nome, String celular, String fixo, String idResponsavel, String professor, String telefoneProfessor, String celularProfessor) throws ClassNotFoundException {
//Esta função recebe da tela RespónsavelProntuário o responsável escolhido pelo usuário        
//Nprontuario.setText(codigo);
        jPanel4.setVisible(true);
        jProntuario.setText(codigo);
        Pesquisar();//refaz a pesquisa original
        NomeresponsavelProntuario.setText(nome);
        JcelularoAluno.setText(celular);
        jTelefoneFixo.setText(fixo);
        jCodigoResponsavel.setText(idResponsavel);
        jNomeProfessor.setText(professor);
        jCelularProfessor.setText(celularProfessor);
        jTelefoneFixoProfessor.setText(telefoneProfessor);
        jPanel3.setVisible(true);
        this.reservarOuEmprestrar = 1;
    }

    public void RecebeReservadeProntuario(String codigo, String nome, String celular, String fixo, String idResponsavel, String professor, String telefoneProfessor, String celularProfessor) throws ClassNotFoundException {
//Esta função recene da tela ResponsávelProntuário qual aluno será reservado o prontuário        
//Nprontuario.setText(codigo);
        label1.setText("Você está RESERVANDO o prontuário para :");
        jButton3.setText("Confirmar Reserva");
        this.reservarOuEmprestrar = 2;
        jPanel4.setVisible(true);
        jProntuario.setText(codigo);
        LimpaTabela();
        Pesquisar();//refaz a pesquisa original
        NomeresponsavelProntuario.setText(nome);
        JcelularoAluno.setText(celular);
        jTelefoneFixo.setText(fixo);
        jCodigoResponsavel.setText(idResponsavel);
        jNomeProfessor.setText(professor);
        jCelularProfessor.setText(celularProfessor);
        jTelefoneFixoProfessor.setText(telefoneProfessor);
        jPanel3.setVisible(true);
    }

    
    

    private boolean ComparaData(LocalDate data) {
        boolean retorno = data.isBefore(LocalDate.now());
        return retorno;

    }

    private void MostraDetalhesProntuario() {
        if(false==(ListarPesquisa.get(0).getStatus().equals("Disponivel"))){
         jPanel3.setVisible(true);
        jPanel4.setVisible(true);
        label1.setText("Detalhes do Prontuário");
        label2.setText(ListarPesquisa.get(0).getStatus() + " para:");
        NomeresponsavelProntuario.setText(ListarPesquisa.get(0).getNome());
        jDateEmprestimoInicio.setDate(ListarPesquisa.get(0).getDataEmprestimo());
        jDateEmprestimoFim.setDate(ListarPesquisa.get(0).getDataDevolução());
        jTelefoneFixo.setText(ListarPesquisa.get(0).getTelefoneFixo());
        JcelularoAluno.setText(ListarPesquisa.get(0).getTelefone());
        jLabel3.setVisible(false);
        jNomeProfessor.setVisible(false);
        jTelefoneFixoProfessor.setVisible(false);
        jCelularProfessor.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jDescricaoProntuario.setText(ListarPesquisa.get(0).getInformacoes());
        jTNprontuario.setText(ListarPesquisa.get(0).getProntuario());
        jTPaciente.setText(ListarPesquisa.get(0).getPaciente());
        if(ListarPesquisa.get(0).getStatus().equals("Reservado")){
        jLStatus.setText("Atualmente reservado para "+ListarPesquisa.get(0).getNome()+" até o dia  "+ConverteDataBrasil(ListarPesquisa.get(0).getDataDevolução()));
        }
        else
            if(ListarPesquisa.get(0).getStatus().equals("Disponível")){
               jLStatus.setText("Atualmente Disponível para empréstimo");
            }
        else
                if(ListarPesquisa.get(0).getStatus().equals("Emprestado")){
                    jLStatus.setText("Emprestado para "+PesquisarProntuario.getNome()+" até o dia "+ConverteDataBrasil(ListarPesquisa.get(0).getDataDevolução()));
                }
    }
    }
    private boolean ComparaDataInicialComDataFinal(LocalDate dataIni, LocalDate dataF) {
    if(dataIni.isAfter(dataF)==true)return true;
    else return false;
    }

    private LocalDate ConverteDataBD(java.util.Date date) {
     DateFormat formataData = DateFormat.getDateInstance();
     String DataString = formataData.format(date);//Converte em String
     String[] dataSeparada = DataString.split("/");
        LocalDate dataConvertida = LocalDate.of(Integer.parseInt(dataSeparada[2]), Integer.parseInt(dataSeparada[1]), Integer.parseInt(dataSeparada[0]));
        return dataConvertida;
     
    }
    private String ConverteDataBrasil(java.util.Date date) {
     DateFormat formataData = DateFormat.getDateInstance();
     String DataString = formataData.format(date);//Converte em String
     
        return DataString;
     
    }

    private boolean VerificaCampoDataVazia() {
    if (jDateEmprestimoInicio.getDate() == null || jDateEmprestimoFim.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Os campos de data são obigatórios");
            return true;
        }
    return false;
    }

    

}